package findthedifference

/**
 * You are given two strings s and t.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Return the letter that was added to t.
 *
 * Input: s = "abcd", t = "abcde"
 * Output: "e"
 *
 * Input: s = "", t = "y"
 * Output: "y"
 *
 * @link https://leetcode.com/problems/find-the-difference/
 */

func findTheDifference(s string, t string) byte {
	sMap := map[rune]int{}
	for _, char := range s {
		if _, ok := sMap[char]; !ok {
			sMap[char] = 0
		}

		sMap[char]++
	}

	tMap := map[rune]int{}
	for _, char := range t {
		if _, ok := tMap[char]; !ok {
			tMap[char] = 0
		}

		tMap[char]++
	}

	for char, count := range tMap {
		cmpCount, ok := sMap[char]
		if !ok {
			return byte(char)
		}

		if count != cmpCount {
			return byte(char)
		}
	}

	return 0
}
